/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class WatermelonTest {
    @Test void example1() {
        Watermelon testApplication = new Watermelon();
        assertEquals("수박수", testApplication.solution(3));
    }

    @Test void example2() {
        Watermelon testApplication = new Watermelon();
        assertEquals("수박수박", testApplication.solution(4));
    }

    @Test void crazy() {
        Watermelon testApplication = new Watermelon();
        assertEquals("수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수", testApplication.solution(31));
    }
}
