/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class Watermelon {

    public String solution(int number) {
        String watermelon = "";

        for (int i = 0; i < number; i += 1) {
            if (i % 2 == 0) {
                watermelon += "수";
            }

            if (i % 2 == 1) {
                watermelon += "박";
            }
        }

        return watermelon;
    }
}
